ALTER TABLE consultation_enquiries
    ADD COLUMN user_account_id BIGINT,
    ADD CONSTRAINT fk_consultation_enquiries_user
        FOREIGN KEY (user_account_id) REFERENCES user_accounts(id) ON DELETE SET NULL;

ALTER TABLE consultation_enquiries DROP CONSTRAINT ck_consultation_enquiries_status;
ALTER TABLE consultation_enquiries ADD CONSTRAINT ck_consultation_enquiries_status
    CHECK (status IN ('NEW', 'CONTACTED', 'CLOSED'));

CREATE INDEX idx_consultation_enquiries_user_created
    ON consultation_enquiries (user_account_id, created_at DESC, id DESC)
    WHERE user_account_id IS NOT NULL;

CREATE TABLE miniapp_programme_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL,
    programme_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_miniapp_favorites_user
        FOREIGN KEY (user_account_id) REFERENCES user_accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_miniapp_favorites_programme
        FOREIGN KEY (programme_id) REFERENCES programmes(id) ON DELETE CASCADE,
    CONSTRAINT uk_miniapp_favorites_user_programme UNIQUE (user_account_id, programme_id)
);

CREATE INDEX idx_miniapp_favorites_user_created
    ON miniapp_programme_favorites (user_account_id, created_at DESC, id DESC);

CREATE TABLE miniapp_study_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL,
    goal VARCHAR(30) NOT NULL,
    subjects JSONB NOT NULL DEFAULT '[]'::jsonb,
    country VARCHAR(100) NOT NULL,
    intake VARCHAR(100),
    education VARCHAR(100) NOT NULL,
    grade VARCHAR(100),
    language VARCHAR(100),
    budget VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_miniapp_plans_user
        FOREIGN KEY (user_account_id) REFERENCES user_accounts(id) ON DELETE CASCADE,
    CONSTRAINT ck_miniapp_plans_goal CHECK (NULLIF(BTRIM(goal), '') IS NOT NULL),
    CONSTRAINT ck_miniapp_plans_country CHECK (NULLIF(BTRIM(country), '') IS NOT NULL),
    CONSTRAINT ck_miniapp_plans_education CHECK (NULLIF(BTRIM(education), '') IS NOT NULL),
    CONSTRAINT ck_miniapp_plans_subjects CHECK (jsonb_typeof(subjects) = 'array'),
    CONSTRAINT ck_miniapp_plans_status CHECK (status IN ('PLANNING', 'COMPLETED'))
);

CREATE INDEX idx_miniapp_plans_user_updated
    ON miniapp_study_plans (user_account_id, updated_at DESC, id DESC);
