ALTER TABLE user_external_identities
    DROP CONSTRAINT ck_user_external_identities_provider;

ALTER TABLE user_external_identities
    ADD CONSTRAINT ck_user_external_identities_provider
        CHECK (provider IN ('WECHAT', 'WECHAT_MINI_PROGRAM'));

CREATE TABLE miniapp_auth_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    token_kind VARCHAR(10) NOT NULL,
    family_id UUID NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    replaced_by_hash VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_miniapp_auth_tokens_account
        FOREIGN KEY (user_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT,
    CONSTRAINT uk_miniapp_auth_tokens_hash UNIQUE (token_hash),
    CONSTRAINT ck_miniapp_auth_tokens_kind CHECK (token_kind IN ('ACCESS', 'REFRESH')),
    CONSTRAINT ck_miniapp_auth_tokens_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_miniapp_auth_tokens_revocation CHECK (
        revoked_at IS NULL OR revoked_at >= created_at
    ),
    CONSTRAINT ck_miniapp_auth_tokens_replacement CHECK (
        replaced_by_hash IS NULL OR replaced_by_hash <> token_hash
    )
);

CREATE INDEX idx_miniapp_auth_tokens_hash_kind
    ON miniapp_auth_tokens (token_hash, token_kind);

CREATE INDEX idx_miniapp_auth_tokens_account_family
    ON miniapp_auth_tokens (user_account_id, family_id);
