CREATE TABLE community_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_account_id BIGINT NOT NULL REFERENCES user_accounts(id),
  body TEXT NOT NULL,
  status VARCHAR(30) NOT NULL,
  comment_count INTEGER NOT NULL DEFAULT 0 CHECK (comment_count >= 0),
  like_count INTEGER NOT NULL DEFAULT 0 CHECK (like_count >= 0),
  risk_reason_code VARCHAR(50),
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT ck_community_post_body CHECK (CHAR_LENGTH(body) BETWEEN 1 AND 2000),
  CONSTRAINT ck_community_post_status CHECK (status IN ('PENDING_REVIEW','PUBLISHED','HIDDEN','DELETED','REJECTED'))
);
CREATE INDEX idx_community_posts_feed ON community_posts(status, published_at DESC, id DESC);
CREATE INDEX idx_community_posts_author ON community_posts(author_account_id, created_at DESC, id DESC);

CREATE TABLE community_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES community_posts(id),
  author_account_id BIGINT NOT NULL REFERENCES user_accounts(id),
  parent_comment_id BIGINT REFERENCES community_comments(id),
  reply_to_account_id BIGINT REFERENCES user_accounts(id),
  body TEXT NOT NULL CHECK (CHAR_LENGTH(body) BETWEEN 1 AND 1000),
  status VARCHAR(30) NOT NULL CHECK (status IN ('PENDING_REVIEW','PUBLISHED','HIDDEN','DELETED','REJECTED')),
  like_count INTEGER NOT NULL DEFAULT 0 CHECK (like_count >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_community_comment_id_post UNIQUE(id, post_id),
  CONSTRAINT fk_community_comment_parent_post FOREIGN KEY(parent_comment_id, post_id)
    REFERENCES community_comments(id, post_id)
);
CREATE INDEX idx_community_comments_post ON community_comments(post_id,status,created_at,id);
CREATE INDEX idx_community_comments_parent ON community_comments(parent_comment_id,status,created_at,id);
CREATE INDEX idx_community_comments_author ON community_comments(author_account_id,created_at DESC,id DESC);

CREATE TABLE community_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL REFERENCES user_accounts(id),
  target_type VARCHAR(10) NOT NULL CHECK (target_type IN ('POST','COMMENT')),
  target_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_community_reaction UNIQUE(account_id,target_type,target_id)
);

CREATE TABLE community_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_account_id BIGINT NOT NULL REFERENCES user_accounts(id),
  target_type VARCHAR(10) NOT NULL CHECK (target_type IN ('POST','COMMENT')),
  target_id BIGINT NOT NULL, reason_code VARCHAR(50) NOT NULL, note VARCHAR(500),
  status VARCHAR(30) NOT NULL CHECK (status IN ('OPEN','RESOLVED_ACTIONED','RESOLVED_REJECTED')),
  handled_by_account_id BIGINT REFERENCES user_accounts(id), handled_at TIMESTAMPTZ,
  resolution_reason_code VARCHAR(50), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX uk_community_open_report ON community_reports(reporter_account_id,target_type,target_id) WHERE status='OPEN';

CREATE TABLE community_moderation_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_account_id BIGINT NOT NULL REFERENCES user_accounts(id), target_type VARCHAR(10) NOT NULL,
  target_id BIGINT NOT NULL, action VARCHAR(30) NOT NULL, reason_code VARCHAR(50) NOT NULL,
  previous_status VARCHAR(30), next_status VARCHAR(30), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE community_user_restrictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL REFERENCES user_accounts(id), restriction_type VARCHAR(10) NOT NULL CHECK (restriction_type IN ('MUTED','BANNED')),
  reason_code VARCHAR(50) NOT NULL, starts_at TIMESTAMPTZ NOT NULL, ends_at TIMESTAMPTZ,
  created_by_account_id BIGINT NOT NULL REFERENCES user_accounts(id), released_at TIMESTAMPTZ,
  released_by_account_id BIGINT REFERENCES user_accounts(id)
);
CREATE TABLE community_idempotency_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL REFERENCES user_accounts(id), operation_type VARCHAR(30) NOT NULL,
  idempotency_key VARCHAR(64) NOT NULL, request_hash VARCHAR(64) NOT NULL, result_target_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_community_idempotency UNIQUE(account_id,operation_type,idempotency_key)
);
