ALTER TABLE programmes
    ADD COLUMN official_url VARCHAR(1000),
    ADD COLUMN source_checked_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN study_pace_display VARCHAR(100),
    ADD CONSTRAINT ck_programmes_official_url_present CHECK (
        official_url IS NULL OR NULLIF(BTRIM(official_url), '') IS NOT NULL
    ),
    ADD CONSTRAINT ck_programmes_study_pace_display_present CHECK (
        study_pace_display IS NULL OR NULLIF(BTRIM(study_pace_display), '') IS NOT NULL
    );

ALTER TABLE programme_intakes
    ADD COLUMN application_deadline DATE,
    ADD COLUMN application_deadline_text VARCHAR(200),
    ADD COLUMN source_url VARCHAR(1000),
    ADD COLUMN source_checked_at TIMESTAMP WITH TIME ZONE,
    ADD CONSTRAINT ck_programme_intakes_deadline_text_present CHECK (
        application_deadline_text IS NULL
        OR NULLIF(BTRIM(application_deadline_text), '') IS NOT NULL
    ),
    ADD CONSTRAINT ck_programme_intakes_source_url_present CHECK (
        source_url IS NULL OR NULLIF(BTRIM(source_url), '') IS NOT NULL
    );

CREATE TABLE programme_detail_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programme_id BIGINT NOT NULL,
    section_type VARCHAR(40) NOT NULL,
    title_zh VARCHAR(200),
    title_en VARCHAR(200),
    body_zh TEXT,
    body_en TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    source_url VARCHAR(1000),
    source_checked_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_programme_detail_sections_programme FOREIGN KEY (programme_id)
        REFERENCES programmes (id) ON DELETE CASCADE,
    CONSTRAINT uk_programme_detail_sections_type UNIQUE (programme_id, section_type),
    CONSTRAINT ck_programme_detail_sections_type CHECK (
        section_type IN (
            'ADMISSIONS',
            'CURRICULUM',
            'LEARNING_OUTCOMES',
            'CAREER_OPPORTUNITIES',
            'IDEAL_STUDENT',
            'OTHER'
        )
    ),
    CONSTRAINT ck_programme_detail_sections_title_present CHECK (
        NULLIF(BTRIM(title_zh), '') IS NOT NULL
        OR NULLIF(BTRIM(title_en), '') IS NOT NULL
    ),
    CONSTRAINT ck_programme_detail_sections_body_present CHECK (
        NULLIF(BTRIM(body_zh), '') IS NOT NULL
        OR NULLIF(BTRIM(body_en), '') IS NOT NULL
    ),
    CONSTRAINT ck_programme_detail_sections_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_programme_detail_sections_source_url_present CHECK (
        source_url IS NULL OR NULLIF(BTRIM(source_url), '') IS NOT NULL
    ),
    CONSTRAINT ck_programme_detail_sections_status CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')
    )
);

CREATE INDEX idx_programme_detail_sections_public
    ON programme_detail_sections (programme_id, status, sort_order, id);
