CREATE TABLE university_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id BIGINT NOT NULL,
    kind VARCHAR(32) NOT NULL,
    asset_url VARCHAR(2000) NOT NULL,
    source_url VARCHAR(2000) NOT NULL,
    source_checked_at TIMESTAMP WITH TIME ZONE,
    licence_raw VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_university_media_university FOREIGN KEY (university_id)
        REFERENCES universities (id) ON DELETE CASCADE,
    CONSTRAINT uk_university_media_asset UNIQUE (university_id, kind, asset_url),
    CONSTRAINT ck_university_media_kind CHECK (kind IN ('LOGO', 'CREST', 'UNIVERSITY_IMAGE')),
    CONSTRAINT ck_university_media_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT ck_university_media_sort_order CHECK (sort_order >= 0)
);

CREATE TABLE programme_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programme_id BIGINT NOT NULL,
    kind VARCHAR(32) NOT NULL,
    asset_url VARCHAR(2000) NOT NULL,
    source_url VARCHAR(2000) NOT NULL,
    source_checked_at TIMESTAMP WITH TIME ZONE,
    licence_raw VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_programme_media_programme FOREIGN KEY (programme_id)
        REFERENCES programmes (id) ON DELETE CASCADE,
    CONSTRAINT uk_programme_media_asset UNIQUE (programme_id, kind, asset_url),
    CONSTRAINT ck_programme_media_kind CHECK (kind = 'COURSE_IMAGE'),
    CONSTRAINT ck_programme_media_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT ck_programme_media_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_university_media_lookup
    ON university_media (university_id, status, sort_order, id);

CREATE INDEX idx_programme_media_lookup
    ON programme_media (programme_id, status, sort_order, id);
