CREATE TABLE inbox_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_account_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
    event_key VARCHAR(200) NOT NULL,
    category VARCHAR(20) NOT NULL CHECK (category IN ('COMMUNITY','SYSTEM','APPLICATION')),
    title VARCHAR(120) NOT NULL,
    body TEXT NOT NULL,
    target_type VARCHAR(30) NOT NULL CHECK (target_type IN ('COMMUNITY_POST','NONE')),
    target_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    read_at TIMESTAMPTZ,
    UNIQUE (recipient_account_id, event_key),
    CHECK ((target_type='NONE' AND target_id IS NULL) OR (target_type='COMMUNITY_POST' AND target_id IS NOT NULL AND target_id>0)),
    CHECK (category='COMMUNITY' OR target_type='NONE')
);
CREATE INDEX inbox_recipient_chronology ON inbox_notifications(recipient_account_id,created_at DESC,id DESC);
CREATE INDEX inbox_recipient_read ON inbox_notifications(recipient_account_id,read_at);
