CREATE TABLE miniapp_wallet_accounts (
    user_account_id BIGINT PRIMARY KEY REFERENCES user_accounts(id) ON DELETE RESTRICT,
    balance_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (balance_amount >= 0),
    points_balance BIGINT NOT NULL DEFAULT 200 CHECK (points_balance >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE miniapp_wallet_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE RESTRICT,
    entry_type VARCHAR(10) NOT NULL CHECK (entry_type IN ('BALANCE','POINTS')),
    direction VARCHAR(10) NOT NULL CHECK (direction IN ('CREDIT','DEBIT')),
    amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    description VARCHAR(120) NOT NULL CHECK (NULLIF(BTRIM(description),'') IS NOT NULL),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_miniapp_wallet_entries_user_time ON miniapp_wallet_entries(user_account_id, occurred_at DESC, id DESC);
