CREATE TABLE countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(2) NOT NULL,
    name_zh VARCHAR(200),
    name_en VARCHAR(200),
    continent_code VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_countries_code UNIQUE (code),
    CONSTRAINT ck_countries_code_format CHECK (code ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_countries_name_present CHECK (
        NULLIF(BTRIM(name_zh), '') IS NOT NULL
        OR NULLIF(BTRIM(name_en), '') IS NOT NULL
    ),
    CONSTRAINT ck_countries_continent_code_format CHECK (
        continent_code ~ '^[A-Z][A-Z0-9_]{0,31}$'
    )
);

CREATE TABLE subject_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name_zh VARCHAR(200),
    name_en VARCHAR(200),
    parent_id BIGINT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_subject_categories_code UNIQUE (code),
    CONSTRAINT fk_subject_categories_parent FOREIGN KEY (parent_id)
        REFERENCES subject_categories (id) ON DELETE RESTRICT,
    CONSTRAINT ck_subject_categories_code_format CHECK (
        code ~ '^[A-Z][A-Z0-9_]{0,63}$'
    ),
    CONSTRAINT ck_subject_categories_name_present CHECK (
        NULLIF(BTRIM(name_zh), '') IS NOT NULL
        OR NULLIF(BTRIM(name_en), '') IS NOT NULL
    ),
    CONSTRAINT ck_subject_categories_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_subject_categories_status CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')
    ),
    CONSTRAINT ck_subject_categories_not_self_parent CHECK (
        parent_id IS NULL OR parent_id <> id
    )
);

CREATE INDEX idx_countries_continent_code
    ON countries (continent_code);

CREATE INDEX idx_subject_categories_parent_id
    ON subject_categories (parent_id);

CREATE INDEX idx_subject_categories_status_sort_order
    ON subject_categories (status, sort_order);
