CREATE TABLE study_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name_zh VARCHAR(200),
    name_en VARCHAR(200),
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_study_levels_code UNIQUE (code),
    CONSTRAINT ck_study_levels_code_format CHECK (
        code ~ '^[A-Z][A-Z0-9_]{0,63}$'
    ),
    CONSTRAINT ck_study_levels_name_present CHECK (
        NULLIF(BTRIM(name_zh), '') IS NOT NULL
        OR NULLIF(BTRIM(name_en), '') IS NOT NULL
    ),
    CONSTRAINT ck_study_levels_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_study_levels_status CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')
    )
);

CREATE TABLE course_modes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name_zh VARCHAR(200),
    name_en VARCHAR(200),
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_course_modes_code UNIQUE (code),
    CONSTRAINT ck_course_modes_code_format CHECK (
        code ~ '^[A-Z][A-Z0-9_]{0,63}$'
    ),
    CONSTRAINT ck_course_modes_name_present CHECK (
        NULLIF(BTRIM(name_zh), '') IS NOT NULL
        OR NULLIF(BTRIM(name_en), '') IS NOT NULL
    ),
    CONSTRAINT ck_course_modes_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_course_modes_status CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')
    )
);

CREATE TABLE languages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(16) NOT NULL,
    name_zh VARCHAR(200),
    name_en VARCHAR(200),
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_languages_code UNIQUE (code),
    CONSTRAINT ck_languages_code_format CHECK (
        code ~ '^[A-Z][A-Z0-9_]{0,15}$'
    ),
    CONSTRAINT ck_languages_name_present CHECK (
        NULLIF(BTRIM(name_zh), '') IS NOT NULL
        OR NULLIF(BTRIM(name_en), '') IS NOT NULL
    ),
    CONSTRAINT ck_languages_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_languages_status CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')
    )
);

ALTER TABLE universities
    ADD COLUMN university_code VARCHAR(64),
    ADD COLUMN name_zh VARCHAR(200),
    ADD COLUMN name_en VARCHAR(200),
    ADD COLUMN city_zh VARCHAR(200),
    ADD COLUMN city_en VARCHAR(200),
    ADD COLUMN description_zh TEXT,
    ADD COLUMN description_en TEXT,
    ADD COLUMN country_id BIGINT,
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN published_at TIMESTAMP WITH TIME ZONE,
    ADD CONSTRAINT uk_universities_university_code UNIQUE (university_code),
    ADD CONSTRAINT fk_universities_country FOREIGN KEY (country_id)
        REFERENCES countries (id) ON DELETE RESTRICT,
    ADD CONSTRAINT ck_universities_university_code_format CHECK (
        university_code IS NULL
        OR university_code ~ '^[A-Z][A-Z0-9_]{0,63}$'
    ),
    ADD CONSTRAINT ck_universities_status CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')
    );

CREATE TABLE programmes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programme_code VARCHAR(64) NOT NULL,
    university_id BIGINT NOT NULL,
    subject_category_id BIGINT NOT NULL,
    study_level_id BIGINT,
    course_mode_id BIGINT,
    slug VARCHAR(200) NOT NULL,
    name_zh VARCHAR(200),
    name_en VARCHAR(200),
    description_zh TEXT,
    description_en TEXT,
    duration_months INTEGER,
    duration_display VARCHAR(100),
    tuition_min NUMERIC(14, 2),
    tuition_max NUMERIC(14, 2),
    tuition_currency CHAR(3),
    tuition_display VARCHAR(200),
    tuition_rmb_min NUMERIC(14, 2),
    tuition_rmb_max NUMERIC(14, 2),
    exchange_rate NUMERIC(18, 8),
    exchange_rate_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uk_programmes_programme_code UNIQUE (programme_code),
    CONSTRAINT uk_programmes_university_slug UNIQUE (university_id, slug),
    CONSTRAINT fk_programmes_university FOREIGN KEY (university_id)
        REFERENCES universities (id) ON DELETE RESTRICT,
    CONSTRAINT fk_programmes_subject_category FOREIGN KEY (subject_category_id)
        REFERENCES subject_categories (id) ON DELETE RESTRICT,
    CONSTRAINT fk_programmes_study_level FOREIGN KEY (study_level_id)
        REFERENCES study_levels (id) ON DELETE RESTRICT,
    CONSTRAINT fk_programmes_course_mode FOREIGN KEY (course_mode_id)
        REFERENCES course_modes (id) ON DELETE RESTRICT,
    CONSTRAINT ck_programmes_code_format CHECK (
        programme_code ~ '^[A-Z][A-Z0-9_]{0,63}$'
    ),
    CONSTRAINT ck_programmes_name_present CHECK (
        NULLIF(BTRIM(name_zh), '') IS NOT NULL
        OR NULLIF(BTRIM(name_en), '') IS NOT NULL
    ),
    CONSTRAINT ck_programmes_duration_months CHECK (
        duration_months IS NULL OR duration_months > 0
    ),
    CONSTRAINT ck_programmes_tuition_min CHECK (
        tuition_min IS NULL OR tuition_min >= 0
    ),
    CONSTRAINT ck_programmes_tuition_max CHECK (
        tuition_max IS NULL OR tuition_max >= 0
    ),
    CONSTRAINT ck_programmes_tuition_range CHECK (
        tuition_min IS NULL
        OR tuition_max IS NULL
        OR tuition_min <= tuition_max
    ),
    CONSTRAINT ck_programmes_tuition_currency_format CHECK (
        tuition_currency IS NULL OR tuition_currency ~ '^[A-Z]{3}$'
    ),
    CONSTRAINT ck_programmes_tuition_currency_present CHECK (
        (tuition_min IS NULL AND tuition_max IS NULL)
        OR tuition_currency IS NOT NULL
    ),
    CONSTRAINT ck_programmes_tuition_rmb_min CHECK (
        tuition_rmb_min IS NULL OR tuition_rmb_min >= 0
    ),
    CONSTRAINT ck_programmes_tuition_rmb_max CHECK (
        tuition_rmb_max IS NULL OR tuition_rmb_max >= 0
    ),
    CONSTRAINT ck_programmes_tuition_rmb_range CHECK (
        tuition_rmb_min IS NULL
        OR tuition_rmb_max IS NULL
        OR tuition_rmb_min <= tuition_rmb_max
    ),
    CONSTRAINT ck_programmes_exchange_rate_positive CHECK (
        exchange_rate IS NULL OR exchange_rate > 0
    ),
    CONSTRAINT ck_programmes_rmb_conversion_present CHECK (
        (tuition_rmb_min IS NULL AND tuition_rmb_max IS NULL)
        OR (exchange_rate IS NOT NULL AND exchange_rate_date IS NOT NULL)
    ),
    CONSTRAINT ck_programmes_status CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')
    )
);

CREATE TABLE programme_languages (
    programme_id BIGINT NOT NULL,
    language_id BIGINT NOT NULL,

    CONSTRAINT pk_programme_languages PRIMARY KEY (programme_id, language_id),
    CONSTRAINT fk_programme_languages_programme FOREIGN KEY (programme_id)
        REFERENCES programmes (id) ON DELETE CASCADE,
    CONSTRAINT fk_programme_languages_language FOREIGN KEY (language_id)
        REFERENCES languages (id) ON DELETE RESTRICT
);

CREATE TABLE programme_intakes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programme_id BIGINT NOT NULL,
    intake_date DATE,
    display_text VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_programme_intakes_programme FOREIGN KEY (programme_id)
        REFERENCES programmes (id) ON DELETE CASCADE,
    CONSTRAINT ck_programme_intakes_display_text CHECK (
        NULLIF(BTRIM(display_text), '') IS NOT NULL
    )
);

CREATE INDEX idx_universities_country_id
    ON universities (country_id);

CREATE INDEX idx_universities_status
    ON universities (status);

CREATE INDEX idx_programmes_university_id
    ON programmes (university_id);

CREATE INDEX idx_programmes_subject_category_id
    ON programmes (subject_category_id);

CREATE INDEX idx_programmes_study_level_id
    ON programmes (study_level_id);

CREATE INDEX idx_programmes_course_mode_id
    ON programmes (course_mode_id);

CREATE INDEX idx_programmes_status
    ON programmes (status);

CREATE INDEX idx_programme_languages_language_id
    ON programme_languages (language_id);

CREATE INDEX idx_programme_intakes_programme_date
    ON programme_intakes (programme_id, intake_date);
