ALTER TABLE programmes
    ADD COLUMN tuition_fee_period VARCHAR(24) NOT NULL DEFAULT 'UNKNOWN',
    ADD COLUMN tuition_total_rmb_min NUMERIC(14, 2),
    ADD COLUMN tuition_total_rmb_max NUMERIC(14, 2),
    ADD CONSTRAINT ck_programmes_tuition_fee_period CHECK (
        tuition_fee_period IN ('PER_YEAR', 'PER_SEMESTER', 'TOTAL_PROGRAM', 'UNKNOWN')
    ),
    ADD CONSTRAINT ck_programmes_tuition_total_rmb_min CHECK (
        tuition_total_rmb_min IS NULL OR tuition_total_rmb_min >= 0
    ),
    ADD CONSTRAINT ck_programmes_tuition_total_rmb_max CHECK (
        tuition_total_rmb_max IS NULL OR tuition_total_rmb_max >= 0
    ),
    ADD CONSTRAINT ck_programmes_tuition_total_rmb_range CHECK (
        tuition_total_rmb_min IS NULL
        OR tuition_total_rmb_max IS NULL
        OR tuition_total_rmb_min <= tuition_total_rmb_max
    );

CREATE TABLE search_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias VARCHAR(200) NOT NULL,
    normalized_alias VARCHAR(200) NOT NULL,
    language VARCHAR(16) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_code VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_search_aliases_normalized_target UNIQUE (
        normalized_alias, language, target_type, target_code
    ),
    CONSTRAINT ck_search_aliases_alias_present CHECK (
        NULLIF(BTRIM(alias), '') IS NOT NULL
    ),
    CONSTRAINT ck_search_aliases_normalized_alias_present CHECK (
        NULLIF(BTRIM(normalized_alias), '') IS NOT NULL
    ),
    CONSTRAINT ck_search_aliases_language_present CHECK (
        NULLIF(BTRIM(language), '') IS NOT NULL
    ),
    CONSTRAINT ck_search_aliases_target_type CHECK (
        target_type IN ('COUNTRY', 'SUBJECT_CATEGORY', 'PROGRAMME')
    ),
    CONSTRAINT ck_search_aliases_target_code_present CHECK (
        NULLIF(BTRIM(target_code), '') IS NOT NULL
    ),
    CONSTRAINT ck_search_aliases_status CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')
    )
);

CREATE INDEX idx_search_aliases_lookup
    ON search_aliases (normalized_alias, status);

CREATE TABLE search_sync_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_search_sync_jobs_status CHECK (
        status IN ('PENDING', 'PROCESSING', 'FAILED')
    ),
    CONSTRAINT ck_search_sync_jobs_attempt_count CHECK (
        attempt_count >= 0
    )
);

CREATE INDEX idx_search_sync_jobs_claim
    ON search_sync_jobs (status, available_at, id);

CREATE INDEX idx_search_sync_jobs_university_id
    ON search_sync_jobs (university_id);
