CREATE TABLE content_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section VARCHAR(20) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    title_zh VARCHAR(300),
    title_en VARCHAR(300),
    summary_zh TEXT,
    summary_en TEXT,
    body_markdown_zh TEXT,
    body_markdown_en TEXT,
    cover_path VARCHAR(500),
    source_name VARCHAR(200),
    source_url VARCHAR(1000),
    author_name VARCHAR(200),
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_content_articles_section_slug UNIQUE (section, slug),
    CONSTRAINT ck_content_articles_section CHECK (
        section IN ('language', 'scholarships', 'programmes', 'news')
    ),
    CONSTRAINT ck_content_articles_slug CHECK (
        slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
    ),
    CONSTRAINT ck_content_articles_status CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')
    ),
    CONSTRAINT ck_content_articles_zh_pair CHECK (
        (title_zh IS NULL AND body_markdown_zh IS NULL)
        OR (
            NULLIF(BTRIM(title_zh), '') IS NOT NULL
            AND NULLIF(BTRIM(body_markdown_zh), '') IS NOT NULL
        )
    ),
    CONSTRAINT ck_content_articles_en_pair CHECK (
        (title_en IS NULL AND body_markdown_en IS NULL)
        OR (
            NULLIF(BTRIM(title_en), '') IS NOT NULL
            AND NULLIF(BTRIM(body_markdown_en), '') IS NOT NULL
        )
    ),
    CONSTRAINT ck_content_articles_language_present CHECK (
        NULLIF(BTRIM(title_zh), '') IS NOT NULL
        OR NULLIF(BTRIM(title_en), '') IS NOT NULL
    ),
    CONSTRAINT ck_content_articles_published_at CHECK (
        status <> 'PUBLISHED' OR published_at IS NOT NULL
    ),
    CONSTRAINT ck_content_articles_source_url CHECK (
        source_url IS NULL OR source_url ~ '^https://[^[:space:]]+$'
    ),
    CONSTRAINT ck_content_articles_cover_path CHECK (
        cover_path IS NULL OR (
            cover_path ~ '^/content/[^[:space:]]+$'
            AND POSITION('..' IN cover_path) = 0
        )
    )
);

CREATE INDEX idx_content_articles_public_list
    ON content_articles (section, published_at DESC, id DESC)
    WHERE status = 'PUBLISHED';
