CREATE TABLE consultation_enquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_code UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    contact VARCHAR(100) NOT NULL,
    intended_school VARCHAR(200),
    intended_course VARCHAR(200),
    qualification VARCHAR(20),
    notes VARCHAR(2000),
    locale VARCHAR(2) NOT NULL,
    privacy_consent BOOLEAN NOT NULL,
    privacy_notice_version VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_consultation_enquiries_reference_code UNIQUE (reference_code),
    CONSTRAINT ck_consultation_enquiries_name CHECK (NULLIF(BTRIM(name), '') IS NOT NULL),
    CONSTRAINT ck_consultation_enquiries_contact CHECK (NULLIF(BTRIM(contact), '') IS NOT NULL),
    CONSTRAINT ck_consultation_enquiries_qualification CHECK (
        qualification IS NULL OR qualification IN ('foundation', 'bachelor', 'master', 'doctorate')
    ),
    CONSTRAINT ck_consultation_enquiries_locale CHECK (locale IN ('zh', 'en')),
    CONSTRAINT ck_consultation_enquiries_privacy_consent CHECK (privacy_consent),
    CONSTRAINT ck_consultation_enquiries_privacy_notice CHECK (
        NULLIF(BTRIM(privacy_notice_version), '') IS NOT NULL
    ),
    CONSTRAINT ck_consultation_enquiries_status CHECK (status = 'NEW')
);

CREATE INDEX idx_consultation_enquiries_created_at
    ON consultation_enquiries (created_at DESC, id DESC);
