CREATE TABLE user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    normalized_email VARCHAR(254),
    normalized_phone VARCHAR(16),
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL,
    email_verified_at TIMESTAMPTZ,
    phone_verified_at TIMESTAMPTZ,
    agreement_version VARCHAR(50) NOT NULL,
    privacy_version VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uk_user_accounts_email UNIQUE (normalized_email),
    CONSTRAINT uk_user_accounts_phone UNIQUE (normalized_phone),
    CONSTRAINT ck_user_accounts_contact CHECK (normalized_email IS NOT NULL OR normalized_phone IS NOT NULL),
    CONSTRAINT ck_user_accounts_status CHECK (status IN ('PENDING_VERIFICATION','ACTIVE','DISABLED','DELETED')),
    CONSTRAINT ck_user_accounts_deleted CHECK ((status = 'DELETED') = (deleted_at IS NOT NULL)),
    CONSTRAINT ck_user_accounts_full_name CHECK (NULLIF(BTRIM(full_name), '') IS NOT NULL),
    CONSTRAINT ck_user_accounts_agreement CHECK (NULLIF(BTRIM(agreement_version), '') IS NOT NULL),
    CONSTRAINT ck_user_accounts_privacy CHECK (NULLIF(BTRIM(privacy_version), '') IS NOT NULL)
);

CREATE TABLE user_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_type VARCHAR(10) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_verification_tokens_user
        FOREIGN KEY (user_id) REFERENCES user_accounts(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_verification_tokens_hash UNIQUE (token_hash),
    CONSTRAINT ck_user_verification_tokens_type CHECK (token_type IN ('EMAIL', 'PHONE')),
    CONSTRAINT ck_user_verification_tokens_hash CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_user_verification_tokens_attempts CHECK (attempts >= 0)
);

CREATE INDEX idx_user_verification_tokens_user_type
    ON user_verification_tokens (user_id, token_type, used_at, expires_at);
CREATE INDEX idx_user_verification_tokens_expiry
    ON user_verification_tokens (expires_at);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_password_reset_tokens_user
        FOREIGN KEY (user_id) REFERENCES user_accounts(id) ON DELETE CASCADE,
    CONSTRAINT uk_password_reset_tokens_hash UNIQUE (token_hash),
    CONSTRAINT ck_password_reset_tokens_hash CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_password_reset_tokens_attempts CHECK (attempts >= 0)
);

CREATE INDEX idx_password_reset_tokens_user
    ON password_reset_tokens (user_id, used_at, expires_at);
CREATE INDEX idx_password_reset_tokens_expiry
    ON password_reset_tokens (expires_at);

CREATE TABLE auth_rate_limit_buckets (
    scope VARCHAR(50) NOT NULL,
    subject_hash VARCHAR(64) NOT NULL,
    attempts INTEGER NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (scope, subject_hash),
    CONSTRAINT ck_auth_rate_limit_buckets_scope CHECK (NULLIF(BTRIM(scope), '') IS NOT NULL),
    CONSTRAINT ck_auth_rate_limit_buckets_subject_hash CHECK (subject_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_auth_rate_limit_buckets_attempts CHECK (attempts >= 0)
);

CREATE INDEX idx_auth_rate_limit_buckets_expiry
    ON auth_rate_limit_buckets (expires_at);

CREATE TABLE spring_session (
    primary_id CHAR(36) NOT NULL PRIMARY KEY,
    session_id CHAR(36) NOT NULL,
    creation_time BIGINT NOT NULL,
    last_access_time BIGINT NOT NULL,
    max_inactive_interval INTEGER NOT NULL,
    expiry_time BIGINT NOT NULL,
    principal_name VARCHAR(100)
);

CREATE UNIQUE INDEX spring_session_ix1 ON spring_session (session_id);
CREATE INDEX spring_session_ix2 ON spring_session (expiry_time);
CREATE INDEX spring_session_ix3 ON spring_session (principal_name);

CREATE TABLE spring_session_attributes (
    session_primary_id CHAR(36) NOT NULL,
    attribute_name VARCHAR(200) NOT NULL,
    attribute_bytes BYTEA NOT NULL,
    PRIMARY KEY (session_primary_id, attribute_name),
    CONSTRAINT spring_session_attributes_fk
        FOREIGN KEY (session_primary_id) REFERENCES spring_session(primary_id) ON DELETE CASCADE
);
