CREATE TABLE user_external_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_client_id VARCHAR(128) NOT NULL,
    provider_subject VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_external_identities_account
        FOREIGN KEY (user_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT,
    CONSTRAINT uk_user_external_identity_subject
        UNIQUE (provider, provider_client_id, provider_subject),
    CONSTRAINT uk_user_external_identity_account_provider
        UNIQUE (provider, user_account_id),
    CONSTRAINT ck_user_external_identities_provider
        CHECK (provider IN ('WECHAT')),
    CONSTRAINT ck_user_external_identities_client_id
        CHECK (NULLIF(BTRIM(provider_client_id), '') IS NOT NULL),
    CONSTRAINT ck_user_external_identities_subject
        CHECK (NULLIF(BTRIM(provider_subject), '') IS NOT NULL),
    CONSTRAINT ck_user_external_identities_login_time
        CHECK (last_login_at >= created_at)
);
